version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd mcart.ui
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - ng build

  post_build:
    commands:
      - aws s3 sync mcart.ui/dist/ s3://mcart-nagp/