version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd mcart.ui
      - npm install -g @angular/cli@15.0.0
  build:
    commands:
      - ls
      - ng build

  post_build:
    commands:
      - aws s3 sync mcart.ui/dist/ s3://mcart-nagp/